### ISSUE TITLE
Add shortcut for rename connection

### ISSUE THREAD

**Issue by invisal** [invisal/query-master#142]
Add "F2" shortcut for rename the connection. You can listen for key down event here (https://github.com/invisal/query-master/blob/main/src/renderer/screens/HomeScreen/index.tsx#L204)

You can add the shortcut key at the Keybinding provider (https://github.com/invisal/query-master/blob/main/src/renderer/contexts/KeyBindingProvider.tsx)

You can use context to access the keybinding

```
  const { binding } = useKeybinding();
  const keyRenaming = binding['rename'];
```

The keybinding has nice method for get the matching

```
keyRenaming.match(e)
```

To trigger rename, you can simply `setRenameSelectedItem(true)`

**Comment by hendrasadewa** [comment]
Hi @invisal  👋, 

I can handle it, can I be assigned to this issue?

**Comment by invisal** [comment]
Fantastic work.

**Comment by hendrasadewa** [comment]
thank u, glad to help!
