### ISSUE TITLE
Some stuffs that we need to improve after I have use 30 minutes

### ISSUE THREAD

**Issue by keppere** [invisal/query-master#3]
1. Tab to fill the auto completion suggestion, current it does not but add `tab` to the current line. The good new it works normally with Enter.
2. It should show loading while it try to fetch or execute query, current it does its job silently
3. Crash when we keep click on previous page button until there is no page to show. Anyway, it does not crash on click on next button, but it seems not to look smart to allow user to click on next page when there is nothing to show
4. Double on connection name to open query panel. It is okay if the connection is correct, but it also open with empty connection string. In this case, I have no way to go back to set my connection but force close and reopen
5. It is super annoying that it cannot remember my connection even I had saved it. I believe that is unintentional 
6. It keeps showing confirmation when I try to run a query. It looks professional to be confirmed. For me personally, it is annoying. It is better to have option not to show.
7. Query tab name should be unique and be able to save.

**Comment by invisal** [comment]
Thanks for your valuable feedback. We will take your feedback seriously and slowly improve those points.
