### ISSUE TITLE
Add row selection support

### ISSUE THREAD

**Issue by invisal** [invisal/query-master#44]
We can extend the OptimizedTable (https://github.com/invisal/query-master/blob/main/src/renderer/components/OptimizeTable/index.tsx) to support row selection.

We should expose two properties:
- `selectedRowsIndex` is an array of index of rows that has been selected
- `onSelectedRowsIndexChanged` will give the array of index when user interact with the table.

How user interact with the table to change the row selection:
- When user click on a cell, it will select a single row
- When user CTRL + Click, it will select another row without deselect the previous row. (this is multiple select).
- When user SHIFT + Click, it will select from previous last row select to the current row (multiple range select).

**Comment by invisal** [comment]
@ebfood if you want to pick this issue up.

**Comment by ebfood** [comment]
I will come to solve this! please assign it to me
