### ISSUE TITLE
Error when connecting to db that does not have table

### ISSUE THREAD

**Issue by thormengkheang** [invisal/query-master#48]
<img width="1136" alt="Screenshot 2023-07-19 at 3 39 58 PM" src="https://github.com/invisal/query-master/assets/8617506/8b3f3ed2-ce61-4617-a303-8a1e9902e4b6">

**Comment by invisal** [comment]
Nice catch. Thanks for reporting.

**Comment by invisal** [comment]
This is fixed in
https://github.com/invisal/query-master/commit/a2fb6629d0e74f9d72c31bc7cca874237dceb4d6

It will be released on the next version.
