### ISSUE TITLE
Request to Add React DevTool

### ISSUE THREAD

**Issue by ebfood** [invisal/query-master#52]
## Description
Hello @invisal. I believe React DevTool is an essential tool for development in our project. During the recent development, I have actually been adding the DevTool locally each time, can we add React DevTool to the project?

## My attempt
I tried [electron-devtools-installer](https://github.com/MarshallOfSound/electron-devtools-installer) , which is already one of the project's dependencies and the recommended approach by the official documentation. However, this method didn't work: [electron issue#36545](https://github.com/electron/electron/issues/36545#issue-1473801670)

Currently, I'm using the workaround mentioned at [react issue#25843](https://github.com/facebook/react/issues/25843#issuecomment-1406766561), which involves temporarily downgrading my extension and loading it locally. However, before each commit, I need to revert the relevant changes.

Do you have any good solutions for this?

**Comment by invisal** [comment]
@ebfood 

I am not sure what is the best approach. One approach is to commit the extension that works and load that extension. I tried https://polypane.app/fmkadmapgofadopljbjfkapdkoienihi.zip  

<img width="479" alt="image" src="https://github.com/invisal/query-master/assets/4539653/33062a09-3c81-4e5d-b003-43c589834a55">

Then, we can load it 

```typescript
app
  .whenReady()
  .then(async () => {
    // Loading the ReactDev Tool
    await session.defaultSession.loadExtension(
      path.join(__dirname, '../../exts/reactdev')
    );
    
    // other code
  }
```

Not sure if this is good solution.

**Comment by ebfood** [comment]
I think this is a good approach, maybe we can use it until upstream makes changes?

**Comment by invisal** [comment]
@ebfood 
https://github.com/invisal/query-master/pull/53

This is proposed solution. If you think it is fine.
