### ISSUE TITLE
Properly syntax highlight MySQL dialet

### ISSUE THREAD

**Issue by invisal** [invisal/query-master#80]
Currently, when we type

```
CREATE DATABASE foo;
```

The database keyword does not highlight as keyword. I believe we didn't config the editor properly to handle MySQL dialet

**Comment by rin-yato** [comment]
From what i saw in the main branch, you didnt pass in a dialect into the sql extension, so it defaults to using the StandardSQL, which has less definition, I think just check for the current database, and pass the correct dialect accordingly will fix this problem.
