### ISSUE TITLE
Schema doesnt update

### ISSUE THREAD

**Issue by rin-yato** [invisal/query-master#90]
When creating a new table, even if it runs successfully, it wont show up in the sidebar. If console.log(schema), it shows outdated schema without the new table that has just been created

**Comment by invisal** [comment]
Yes. We are aware of this problem and there are simple solution to fix this one. Let me write how we can achieve it.

https://github.com/invisal/query-master/blob/main/src/renderer/contexts/SwitchDatabaseProvider.tsx#L15
This file listen to all SQL that got executed. Currently, it listens for `USE`. We can also listen for `CREATE TABLE` and `CREATE DATABASES`.
